services:
  - type: web
    name: trash-classifier-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    env: python
    region: singapore
    plan: free
    branch: main
    buildFilter:
      paths:
        - APIBroo.py
        - templates/index.html
    autoDeploy: true

build:
  commands:
    # ไม่ต้องมีการติดตั้ง dependencies ซ้ำในที่นี้
