services:
  - type: web
    name: trash-classifier-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn APIBroo:app
    env: python
    region: singapore
    plan: free
    branch: main
    buildFilter:
      paths:
        - APIBroo.py
        - render.yaml
        - requirements.txt
        - .gitignore
    autoDeploy: true

build:
  commands:
    - pip install --upgrade pip  # อัพเกรด pip ให้เป็นเวอร์ชันล่าสุด
    - pip install -r requirements.txt  # ติดตั้ง dependencies จาก requirements.txt
