services:
  - type: web
    name: trash-classifier-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    env: python
    region: singapore
    plan: free
    branch: main
    buildFilter:
      paths:
        - APIBroo.py
        - model/trash_classifier_model.h5
        - templates/index.html
    autoDeploy: true

build:
  commands:
    # ไม่ต้องมี pip install อีกในส่วนนี้ เพราะมันได้ระบุไว้ใน buildCommand ของ services แล้ว
    - # pip install -r requirements.txt  # ตัดออก
