services:
  - type: web
    name: trash-classifier-api
    runtime: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn app:app
    env: python
    region: singapore  # หรือ singapore, frankfurt, ฯลฯ
    plan: free
    branch: main
    buildFilter:
      paths:
        - APIBroo.py
        - model/trash_classifier_model.h5
        - templates/index.html
    autoDeploy: true

build:
  commands:
    - pip install --upgrade pip  # อัปเดต pip ก่อนติดตั้ง dependencies
    - pip install -r requirements.txt  # ติดตั้ง dependencies จาก requirements.txt
